In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [2]:
dataFolder = 'data/'
dataFile = dataFolder + "iris.csv"
print(dataFile)

data/iris.csv


In [3]:
df = pd.read_csv(dataFile)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

       species  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [4]:
X = df.iloc[:,0:3].values
y = df.iloc[:,4].values

In [5]:
print(X[0:5])
print(y[0:5])

[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [6]:
print(X.shape)
print(y.shape)

(150, 3)
(150,)


In [7]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [8]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print(X_train[0:5])

[[6.4 3.1 5.5]
 [5.4 3.  4.5]
 [5.2 3.5 1.5]
 [6.1 3.  4.9]
 [6.4 2.8 5.6]]


In [11]:
print(y_train[0:5])
print(X_test[0:5])
print(y_test[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]
[[5.8 2.8 5.1]
 [6.  2.2 4. ]
 [5.5 4.2 1.4]
 [7.3 2.9 6.3]
 [5.  3.4 1.5]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]


In [12]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3)
  ])
model

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=50, epochs=100)        

2021-08-22 08:41:46.257865: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-22 08:41:46.371302: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/100
3/3 [==============================] - 1s 2ms/step - loss: 6.3014 - accuracy: 0.3667
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 6.1762 - accuracy: 0.3667
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 6.1021 - accuracy: 0.3667
Epoch 4/100
3/3 [==============================] - 0s 1ms/step - loss: 6.0333 - accuracy: 0.3667
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 5.9570 - accuracy: 0.3667
Epoch 6/100
3/3 [==============================] - 0s 2ms/step - loss: 5.9115 - accuracy: 0.3667
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 5.9101 - accuracy: 0.3667
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 5.9101 - accuracy: 0.3667
Epoch 9/100
3/3 [==============================] - 0s 3ms/step - loss: 5.9100 - accuracy: 0.3667
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 5.9100 - accuracy: 0.3667
Epoch 11/100
3/3 [===========

In [13]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 3.2239091396331787
Test accuracy: 0.20000000298023224


In [14]:
y_pred = model.predict(X_test)
y_pred

array([[-1.4091141, -3.268493 ,  2.4518342],
       [-1.2899247, -2.9220471,  2.3113172],
       [-1.7839977, -2.1338558,  2.2152898],
       [-1.684777 , -4.155386 ,  3.0112975],
       [-1.4887946, -1.8080134,  1.9768999],
       [-1.5442951, -3.7222362,  2.7054133],
       [-1.5273447, -1.8018569,  1.9835317],
       [-1.5296817, -3.2828677,  2.65283  ],
       [-1.5114105, -3.391662 ,  2.6697526],
       [-1.3750862, -2.8672726,  2.3813586],
       [-1.4452887, -3.5887206,  2.5757718],
       [-1.4933176, -3.106698 ,  2.556377 ],
       [-1.4231341, -3.1707094,  2.4779372],
       [-1.4627913, -3.2288494,  2.5658653],
       [-1.4353893, -3.1573515,  2.4853723],
       [-1.3874085, -1.677816 ,  1.911663 ],
       [-1.4100308, -3.0452833,  2.4323473],
       [-1.3082498, -2.9151487,  2.269089 ],
       [-1.3514986, -1.608954 ,  1.8679643],
       [-1.6864871, -1.9791098,  2.1472952],
       [-1.3712455, -3.1311202,  2.3727098],
       [-1.375765 , -2.9304378,  2.3380578],
       [-1

In [17]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

print(f'Training Set Accuracy: {(predicted == actual).mean() * 100:f}')

Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


/var/folders/z2/6mdbpjn556s1zb_dqy_hj6lr0000gn/T/ipykernel_70318/1831638829.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(f'Training Set Accuracy: {(predicted == y_test).mean() * 100:f}')


AttributeError: 'bool' object has no attribute 'mean'